concurrent = 1
check_interval = 0
shutdown_timeout = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "Kiro-Local-Runner"
  url = "https://gitlab.huixuanjiasu.com/"
  id = 1081
  token = "mRyJ6ZTr6sEhk7Npyxv7"
  token_obtained_at = 2026-01-16T12:25:31Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "shell"
  shell = "powershell"
  [runners.custom_build_dir]
  [runners.cache]
    MaxUploadedArchiveSize = 0
  [runners.cache.s3]
  [runners.cache.gcs]
  [runners.cache.azure]
  tags = ["windows"]
